# Generated by Django 5.2.2 on 2025-06-08 11:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencySettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('safety_check_interval', models.IntegerField(default=15)),
                ('emergency_check_interval', models.IntegerField(default=5)),
                ('first_escalation_timeout', models.IntegerField(default=2)),
                ('second_escalation_timeout', models.IntegerField(default=5)),
                ('authority_notification_timeout', models.IntegerField(default=10)),
                ('max_contact_attempts', models.IntegerField(default=3)),
                ('contact_retry_interval', models.IntegerField(default=1)),
                ('police_number', models.CharField(default='911', max_length=20)),
                ('medical_number', models.CharField(default='911', max_length=20)),
                ('fire_number', models.CharField(default='911', max_length=20)),
                ('safe_zone_radius', models.IntegerField(default=1000)),
                ('danger_zone_enabled', models.BooleanField(default=True)),
                ('notify_emergency_contacts', models.BooleanField(default=True)),
                ('notify_platform_admin', models.BooleanField(default=True)),
                ('auto_call_authorities', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Emergency Settings',
                'verbose_name_plural': 'Emergency Settings',
                'db_table': 'emergency_settings',
            },
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('panic', 'Panic Button'), ('accident', 'Accident'), ('harassment', 'Harassment'), ('vehicle_breakdown', 'Vehicle Breakdown'), ('medical', 'Medical Emergency'), ('security', 'Security Threat'), ('other', 'Other Emergency')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('responding', 'Responding'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=10)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('address', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('audio_recording', models.FileField(blank=True, null=True, upload_to='emergency/audio/')),
                ('photos', models.JSONField(blank=True, default=list)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('escalated', models.BooleanField(default=False)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_level', models.IntegerField(default=1)),
                ('police_notified', models.BooleanField(default=False)),
                ('police_case_number', models.CharField(blank=True, max_length=50, null=True)),
                ('medical_services_notified', models.BooleanField(default=False)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_alerts', to='rides.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emergency_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('relationship', models.CharField(choices=[('family', 'Family Member'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('spouse', 'Spouse'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emergency_contacts',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyResponse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('contact_emergency_contacts', 'Contact Emergency Contacts'), ('notify_authorities', 'Notify Authorities'), ('dispatch_security', 'Dispatch Security'), ('track_location', 'Track Location'), ('call_user', 'Call User'), ('send_help', 'Send Help'), ('escalate', 'Escalate'), ('close_case', 'Close Case')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contact_attempts', models.IntegerField(default=0)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='emergency.emergencyalert')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emergency_responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationShare',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_type', models.CharField(choices=[('emergency', 'Emergency Share'), ('ride', 'Ride Share'), ('manual', 'Manual Share')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('share_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_shares', to='emergency.emergencyalert')),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_shares', to='rides.ride')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='received_location_shares', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'location_shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyCheck',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_type', models.CharField(choices=[('automatic', 'Automatic Check'), ('manual', 'Manual Check'), ('scheduled', 'Scheduled Check'), ('emergency', 'Emergency Check')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('missed', 'Missed'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('is_safe', models.BooleanField(blank=True, null=True)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('escalated', models.BooleanField(default=False)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_checks', to='rides.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safety_checks',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emergencyalert',
            index=models.Index(fields=['status', 'severity'], name='emergency_a_status_8fabd6_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyalert',
            index=models.Index(fields=['user', 'created_at'], name='emergency_a_user_id_2c7f20_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyalert',
            index=models.Index(fields=['ride'], name='emergency_a_ride_id_f08ebf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emergencycontact',
            unique_together={('user', 'phone_number')},
        ),
        migrations.AddIndex(
            model_name='emergencyresponse',
            index=models.Index(fields=['alert', 'status'], name='emergency_r_alert_i_169f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyresponse',
            index=models.Index(fields=['assigned_to'], name='emergency_r_assigne_158105_idx'),
        ),
        migrations.AddIndex(
            model_name='locationshare',
            index=models.Index(fields=['user', 'is_active'], name='location_sh_user_id_09ec76_idx'),
        ),
        migrations.AddIndex(
            model_name='locationshare',
            index=models.Index(fields=['share_token'], name='location_sh_share_t_a85620_idx'),
        ),
        migrations.AddIndex(
            model_name='safetycheck',
            index=models.Index(fields=['ride', 'status'], name='safety_chec_ride_id_9d514e_idx'),
        ),
        migrations.AddIndex(
            model_name='safetycheck',
            index=models.Index(fields=['scheduled_at'], name='safety_chec_schedul_088cc9_idx'),
        ),
    ]
